export const presupMockup = {
    "customer": {
        "name": "",
        "ape": "",
        "domicilio": {
            "calle": "",
            "ciudad": "",
            "cp": "",
            "entre": "",
            "lat": null,
            "lon": null,
            "nro": "",
            "ofi": "",
            "piso": "",
        },
        "contacto": {
            "email": "",
            "cel_car": "",
            "cel_nbr": "",
            "cel_pre": "",
            "tel_car": "",
            "tel_nbr": "",
            "tel_pre": "",
            "fax_car": "",
            "fax_nbr": "",
            "fax_pre": "",
        },
    },
    "oper": {
        "categoria": "Insta. común",
        "creado": "",
        "formapago": "",
        "insta_id": 1,
        "intobserv": "",
        "intobserv_new": "",
        "modo_facturacion": "",
        "observ": "",
        "presup_id": 5,
        "prior": 3,
        "reboteobserv": null,
        "rubro_id": 4,
        "signature": null,
        "status": "Creado",
        "tecobserv": null,
        "tipo_cond_pago": "",
        "tipo_pago": "otra",
        "vend_id": 1,
    },
    "const": {
        // ! Valores que la app no puede modificar
        "account_id": null,
        "ainsta": null,
        "atendido_por": null,
        "call_id": null, // ! Id del item de agenda desde donde se crea
        "cierre": null,
        "closeobserv": "",
        "customer_id": null,
        "en_not_observ": null,
        "explic_observ": null,
        "killobserv": null,
        "muerto": null,
        "rebote": null,
        "suspobs": null,
        "whoainsta": null,
        "whoclose": null,
        "whocreado": null,
        "whokill": null,
        "whorebote": null,
    },
    "abono": {
        "abono": 0,
        "bonif_abono": "0.15",
        "bonif_meses": 3,
        "bonifd": 0,
        "bonifp_perc": '0.00',
        "bonifp": "0.00",
        "bonifpPercAux": 0,
        "dolar": "",
        "insta": null,
        "materiales": 0,
        "presup_id": 0,
    },
    "items": {}
}